module.exports = [
  {
    id: 1,
    name: "normal",
    no_damage_to: ["ghost"],
    half_damage_to: ["rock", "steel"],
    double_damage_to: [],
  },
  {
    id: 2,
    name: "fighting",
    no_damage_to: ["ghost"],
    half_damage_to: ["flying", "poison", "bug", "psychic", "fairy"],
    double_damage_to: ["normal", "rock", "steel", "ice", "dark"],
  },
  {
    id: 3,
    name: "flying",
    no_damage_to: [],
    half_damage_to: ["rock", "steel", "electric"],
    double_damage_to: ["fighting", "bug", "grass"],
  },
  {
    id: 4,
    name: "poison",
    no_damage_to: ["steel"],
    half_damage_to: ["poison", "ground", "rock", "ghost"],
    double_damage_to: ["grass", "fairy"],
  },
  {
    id: 5,
    name: "ground",
    no_damage_to: ["flying"],
    half_damage_to: ["bug", "grass"],
    double_damage_to: ["poison", "rock", "steel", "fire", "electric"],
  },
  {
    id: 6,
    name: "rock",
    no_damage_to: [],
    half_damage_to: ["fighting", "ground", "steel"],
    double_damage_to: ["flying", "bug", "fire", "ice"],
  },
  {
    id: 7,
    name: "bug",
    no_damage_to: [],
    half_damage_to: ["fighting", "flying", "poison", "ghost", "steel", "fire", "fairy"],
    double_damage_to: ["grass", "psychic", "dark"],
  },
  {
    id: 8,
    name: "ghost",
    no_damage_to: ["normal"],
    half_damage_to: ["dark"],
    double_damage_to: ["ghost", "psychic"],
  },
  {
    id: 9,
    name: "steel",
    no_damage_to: [],
    half_damage_to: ["steel", "fire", "water", "electric"],
    double_damage_to: ["rock", "ice", "fairy"],
  },
  {
    id: 10,
    name: "fire",
    no_damage_to: [],
    half_damage_to: ["rock", "fire", "water", "dragon"],
    double_damage_to: ["bug", "steel", "grass", "ice"],
  },
  {
    id: 11,
    name: "water",
    no_damage_to: [],
    half_damage_to: ["water", "grass", "dragon"],
    double_damage_to: ["ground", "rock", "fire"],
  },
  {
    id: 12,
    name: "grass",
    no_damage_to: [],
    half_damage_to: ["flying", "poison", "bug", "steel", "fire", "dragon", "grass"],
    double_damage_to: ["ground", "rock", "water"],
  },
  {
    id: 13,
    name: "electric",
    no_damage_to: ["ground"],
    half_damage_to: ["grass", "electric", "dragon"],
    double_damage_to: ["flying", "water"],
  },
  {
    id: 14,
    name: "psychic",
    no_damage_to: ["dark"],
    half_damage_to: ["steel", "psychic"],
    double_damage_to: ["fighting", "poison"],
  },
  {
    id: 15,
    name: "ice",
    no_damage_to: [],
    half_damage_to: ["steel", "fire", "water", "ice"],
    double_damage_to: ["flying", "ground", "grass", "dragon"],
  },
  {
    id: 16,
    name: "dragon",
    no_damage_to: ["fairy"],
    half_damage_to: ["steel"],
    double_damage_to: ["dragon"],
  },
  {
    id: 17,
    name: "dark",
    no_damage_to: [],
    half_damage_to: ["fighting", "dark", "fairy"],
    double_damage_to: ["ghost", "psychic"],
  },
  {
    id: 18,
    name: "fairy",
    no_damage_to: [],
    half_damage_to: ["poison", "steel", "fire"],
    double_damage_to: ["fighting", "dragon", "dark"],
  },
];
